# Generated by Django 3.1.5 on 2021-02-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocapp', '0001_initial'),
        ('categoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylist',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voclist', to='vocapp.voclist'),
        ),
        migrations.AlterField(
            model_name='categorylist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
