# Generated by Django 3.1.5 on 2021-02-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0003_auto_20210203_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorylist',
            name='content',
        ),
    ]
