# Generated by Django 3.1.5 on 2021-02-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='vocapp.voclist')),
            ],
        ),
    ]
