# Generated by Django 3.1.5 on 2021-01-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voclist',
            fields=[
                ('voc_no', models.AutoField(primary_key=True, serialize=False)),
                ('voc_date', models.DateTimeField()),
                ('voc_method', models.CharField(max_length=50)),
                ('client_number', models.TextField()),
                ('client_name', models.TextField()),
                ('voc_number', models.TextField()),
                ('voc_title', models.TextField()),
                ('voc_content', models.TextField()),
                ('voc_comment', models.TextField()),
                ('voc_manger', models.CharField(max_length=50)),
                ('report', models.CharField(max_length=50)),
                ('partner', models.CharField(max_length=50)),
                ('category_name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
