# Generated by Django 3.1.5 on 2021-02-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voclist',
            name='category_name',
        ),
        migrations.AddField(
            model_name='voclist',
            name='category_num',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
