# Generated by Django 3.1.5 on 2021-02-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocapp', '0003_auto_20210203_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voclist',
            name='category_num',
        ),
    ]
