# Generated by Django 3.1.5 on 2021-02-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocapp', '0002_auto_20210203_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voclist',
            name='category_num',
            field=models.IntegerField(null=True),
        ),
    ]
