# Generated by Django 3.1.5 on 2021-02-03 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0004_remove_categorylist_content'),
        ('vocapp', '0004_remove_voclist_category_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='voclist',
            name='category_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categoryapp.categorylist'),
        ),
    ]
